//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scooter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notifications
    {
        public int NotificaionId { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string ExtraColumn { get; set; }
    }
}
